import type { Metadata } from "next";
import { Fraunces, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toast";

const plexSans = IBM_Plex_Sans({subsets:['latin'], variable:'--font-plex-sans'});
const fraunces = Fraunces({subsets:['latin'], variable:'--font-fraunces'});

export const metadata: Metadata = {
  title: "JobTracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      suppressHydrationWarning
      className={cn("h-full", fraunces.variable, plexSans.variable)}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster  />
      </body>
    </html>
  );
}
